#!/bin/bash

### BEGIN INIT INFO
# Provides:          tap
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TAP startup script 
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# tap
# description: TAP - Remote Penetration Testing Platform
# processname: tap

DAEMON_PATH="/usr/share/tap/src/core/"

DAEMON=/usr/share/tap/src/core/heartbeat.py
DAEMONOPTS=""

NAME=tap
DESC="TAP Remote Pentesting platform"
PIDFILE=/var/run/tap.pid
SCRIPTNAME=/etc/init.d/tap

case "$1" in
start)
    printf "%-50s" "Starting TAP - the remote pentesting platform."
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking TAP..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping TAP - JERONIMOOOOOOOOOOOOooooooo!"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill $PID
	    ps -ef | grep /usr/share/tap/tap.py | grep -v grep | awk '{print $2}' | xargs kill -9
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
